### ISSUE TITLE
Does the training data contain tscn files?

### ISSUE THREAD

**Issue by rick2047** [minosvasilias/godot-dodo#2]
A good thing in Godot is that the tscn format is just text. I was wondering if we can include tscn examples in the training data, we might then be able to just add things to the scene with a prompt.

**Comment by minosvasilias** [comment]
It doesn't, only GDScript.

Since the premise of this project was to train single-language models that specialize in highest-possible performance for only that language, it wouldn't make sense to include `.tscn` files in the dataset.

However, it would certainly be possible to train a separate model on just `.tscn` files.

I have my doubts about whether that would yield better results than just asking a GDScript model to generate code to populate a scene, and then executing that code automatically. Have no conclusive evidence either way though, past some rudimentary tests trying to populate scenes using `gpt-4`.
